FROM ghcr.io/arctux-linux/arctux/base:latest

LABEL org.opencontainers.image.source=https://github.com/arctux-linux/arctux
LABEL org.opencontainers.image.description="Arctux Linux: base OS with development dependencies"
LABEL org.opencontainers.image.licenses=MIT

RUN pacman -S --noconfirm base-devel
