FROM ghcr.io/vially/archlinuxarm/base:latest

LABEL org.opencontainers.image.source=https://github.com/vially/archlinuxarm
LABEL org.opencontainers.image.description="Arch Linux ARM: base OS with development dependencies"
LABEL org.opencontainers.image.licenses=MIT

RUN pacman -S --noconfirm base-devel
